### ISSUE TITLE
Error running create_postprocess when geyser is down

### ISSUE THREAD

**Issue by alperaltuntas** [NCAR/CESM_postprocessing#121]
We get the following error when geyser is down, although we run the tool on cheyenne:

```
$ create_postprocess -caseroot test 
create_postprocess ERROR: please set the POSTPROCESS_PATH_GEYSER environment variable. For example, setenv POSTPROCESS_PATH_GEYSER /glade/p/cesm/postprocessing_geyser
```

When I set POSTPROCESS_PATH to my local copy, which is an earlier version (where the latest commit is 9c8441f2c4f719b87dd4e07c8f99b82894637d9f - Dec 18), however, create_postprocess works fine, so I guess this is a bug introduced lately?

**Comment by bertinia** [comment]
@alperaltuntas - Actually, this is a new feature that is documented in the updated
[Cheyenne and Geyser quick start wiki page](https://github.com/NCAR/CESM_postprocessing/wiki/cheyenne-and-geyser-quick-start-guide)

we have to maintain 2 separate python virtualenv builds for geyser and cheyenne because
1. the modules and underlying library dependencies are different for the different architectures
2. the batch systems are different where cheyenne uses PBS and geyser uses slurm

If you are working from you own sandboxes, you'll want to create one vitualenv for cheyenne
using:
`create_python_env -machine cheyenne`
and then point the POSTPROCESS_PATH env var to that location. 

And then create another virtualenv for geyser in a separate dir using another clone as follows:
`execgy`
`create_python_env -machine geyser`
and set the POSTPROCESS_PATH_GEYSER to point to this dir. 

I've also prebuilt the most current versions of the postprocessing virutalenv on glade so that:
`POSTPROCESS_PATH = /glade/p/cesm/postprocessing_ch`
`POSTPROCESS_PATH_GEYSER = /glade/p/cesm/postprocessing_geyser`
will work for most users. 

Once you have these virtualenv's build and the env vars correct, then when you run
`create_postprocess --caseroot [path-to-case]`
you will see 2 submission scripts for each postprocessing task corresponding to cheyenne and
geyser indicated by [script_name]_geyser.

For example, for ocean diagnostics, the cheyenne scripts are:
`ocn_averages`
`ocn_diagnostics`
Each is submitted using `bsub` on a cheyenne login node.

The corresponding geyser scripts are:
`ocn_averages_geyser`
`ocn_diagnostics_geyser`
Each is submitted using `sbatch` from **either a cheyenne login node or a geyser interactive session.**

Important note for hi-res ocn diags, the `slurm` batch system allows for user specified memory requests up to 1000G per node. This may allow us to get more years through the pyAverager which is currently memory bound when running with hi-res data.
