### ISSUE TITLE
allow existing output files

### ISSUE THREAD

**Issue by lvankampenhout** [NCAR/CESM_postprocessing#183]
I guess this is a feature request. I am repeatedly generating timeseries of a run that is ongoing. It appears that the `timeseries` tool is not fit for that because I receive the following error messages: 

```
Found existing output files for time-series variables: Q
(...)
```
after which the run aborts. 

My use case is that I'm generating monthly files containing 6-hourly data of selected atmospheric variables. I processed the first 10 years of simulation which already gave me 500 GB of output. I feels weird throwing away this data in order to process the next 10 years, and so on. 

The best solution would be that the timeseries tools somehow recognizes its own files that it produced earlier (e.g. based on the name) and skips those months. 

Another solution  would be that you can specify the range of years for which you want to make timeseries. For instance, I now processed 1950-1960 so I can skip those years now and proceed with 1960-1970. There is currently no option in the `env_timeseries.xml` to specify bounds to the files (the tool simply takes everything it can find).

**Comment by bertinia** [comment]
@lvankampenhout - a couple of suggestions... in the env_postprocess.xml, there is an XML variable:

`<entry id="TIMESERIES_COMPLETECHUNK" value="FALSE" />`

This option will generate timeseries with the history data files available regardless of whether or not there are enough time slices to satisfy the env_timeseries.xml variable:

`<tseries_filecat_n>1000</tseries_filecat_n>`

The logs/ts_status.log JSON file keeps track of which time slices have been converted to single-variable timeslices and is used by the chunking.py code to figure out if more data needs to be appended to a given single-variable timeseries file in order to satisfy the requested chunk size. 

One thing to keep in mind is that if you have existing single-variable timeseries files completed and then generate more history slice data with the model and subsequently run the timeseries generation again, you will get a new set of single-variable timeseries file corresponding to the additional model years that have been run. This is by design. 

A scenario from @sherimickelson explains this further:

> Say you know you want to concatenate 10 years of data, but are only running two years at a time.  For the reshaper to concatenate, it has to have the same file name.  So for this to work the timeseries files would have to have the date 000101-00912.  The problem is that we don't know if there will ever be that much data in the file from an automated sense and the file name is misleading because it may not contain all of those timeslices.  
> 
> What it does with the complete chunk option is that it waits to create that file until all of the data is there.  Otherwise, it'll create what it sees and names it to what slices are in the file.
> 
> The best option is to concatenate the files with nco if you can only do 1 at a time.  
> 

We have talked about adding the ability to specify years and/or variables to the timeseries generation and have opted not to do that for the CMIP6 automated workflow. This is so that we can keep the timeseries generation script calls to the pyReshaper tool as light weight and performant as possible.

**Comment by lvankampenhout** [comment]
Hi Alice, thanks for your elaborate response. 

Regarding

> The logs/ts_status.log JSON file keeps track of which time slices have been converted to single-variable timeslices and is used by the chunking.py code to figure out if more data needs to be appended to a given single-variable timeseries file in order to satisfy the requested chunk size.

This may actually be the source of may problem. I removed the `logs/ts_status.log` file at some point after I kept getting messages which suggested to me that it had corrupted: 
```
Extra data: line 1 column 1058 - line 1 column 134229 (char 1057 - 134228)
```

But by reading your response above, this file is quite crucial to the behaviour of the timeseries script and should not be removed after one or more timeseries have been created. 

I just wanted to re-iterate that in my example, the chunk size is quite small (1 month) compared to the number of years that I'm adding each time (10 years), which I believe makes it different from the example that Sheri gave. Anyway, I will try again from scratch and let you know how it goes.
