### ISSUE TITLE
ocn model_vs_control can't handle multiple comparisons

### ISSUE THREAD

**Issue by jtruesdal** [NCAR/CESM_postprocessing#20]
The ocean diagnostics for model vs control are not general enough to handle more than one comparisons.  Running successive model_vs_control experiments against different controls makes use of the same generic directory with the later comparisons overwriting the earlier ones. The other components use directory names that are composed of the actual model and control case names and are unique.  Implementing something like this would allow us to make several comparisons to different controls.

**Comment by bertinia** [comment]
Fixed in:
https://svn-ccsm-models.cgd.ucar.edu/postprocessing/trunk_tags/postprocessing_20160620

NOTE - the index.html will need to be manually updated to link to the multiple comparisons for a given run because there is no way (currently) for one run of the diags to be able to remember a previous run and update the index.html accordingly. Please open another issue if this manually editing becomes a problem. We can also address it in the copy_html utility that will present a unified page for all diag types.
